env:
  - DJANGO=2.2
  - DJANGO=3.0
language: python
python:
  - "3.7"
  - "3.8"
services:
  - postgresql
install:
  - pip install django==${DJANGO}
  - "pip install psycopg2 git+https://github.com/mediapredict/django-hstore.git@v1.4.3"
  - "pip install ."
addons:
  postgresql: "11"
before_script:
  - psql -c 'create database daffodil_hstore_test;' -U postgres
  - psql daffodil_hstore_test -c 'CREATE EXTENSION IF NOT EXISTS hstore;' -U postgres
  - python setup.py install
script: python test/tests.py
