env:
  - DJANGO=2.2
  - DJANGO=3.0
language: python
python:
  - "3.7"
  - "3.8"
services:
  - postgresql
before_install:
    - sudo apt-get update
    - sudo apt-get --yes remove postgresql\*
    - sudo apt-get install -y postgresql-12 postgresql-client-12
    - sudo service postgresql restart 12
install:
  - pip install psycopg2-binary==2.8.4
  - pip install django==${DJANGO}
  - "pip install ."
addons:
  postgresql: "12"
before_script:
  - psql -c 'create database daffodil_hstore_test;' -U postgres
  - psql daffodil_hstore_test -c 'CREATE EXTENSION IF NOT EXISTS hstore;' -U postgres
  - python setup.py install
script: python test/tests.py
