env:
  - DJANGO=3.0
  - DJANGO=3.2.7
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
before_install:
  - sudo apt-get update
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql stop
  - sudo service postgresql start 12
  - sleep 1
install:
  - pip install psycopg2-binary==2.8.4
  - pip install django==${DJANGO}
  - "pip install ."
before_script:
  - psql -c 'create database daffodil_hstore_test;' -U postgres
  - psql daffodil_hstore_test -c 'CREATE EXTENSION IF NOT EXISTS hstore;' -U postgres
  - python setup.py install
script: python test/tests.py
